In [1]:
# sample data deret waktu 
# import modules
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.3.3
2.3.5

In [2]:
# persiapan data frame

## DEPRICATED ##
# n_rows = 365 * 24
# n_cols = 2
# cols = ['col1', 'col2']

# df = pd.DataFrame(np.random.randint(1, 20, size=(n_rows, n_cols)), 
#                   columns=cols)

# df.index = pd.util.testing.makeDateIndex(n_rows, freq='H')
# df

n_rows = 365 * 24 
n_cols = 2         
cols = ['col1', 'col2'] 

df = pd.DataFrame(np.random.randint(1, 20, size=(n_rows, n_cols)), columns=cols)

df.index = pd.date_range(start='2023-01-01', periods=n_rows, freq='h')

df.head()

                     col1  col2
2023-01-01 00:00:00     1     9
2023-01-01 01:00:00     5     2
2023-01-01 02:00:00    15    17
2023-01-01 03:00:00     1     1
2023-01-01 04:00:00     1    14

In [3]:
# resampling data dgn interval/bulan
df.resample('M')['col1'].sum().to_frame()

C:\Users\COMPUTER\AppData\Local\Temp\ipykernel_26108\1174992793.py:2: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  df.resample('M')['col1'].sum().to_frame()

            col1
2023-01-31  7489
2023-02-28  6792
2023-03-31  7603
2023-04-30  7113
2023-05-31  7643
2023-06-30  7375
2023-07-31  7553
2023-08-31  7491
2023-09-30  6982
2023-10-31  7483
2023-11-30  7247
2023-12-31  7374

In [4]:
# resampling data dgn interval/hari
df.resample('D')['col1'].sum().to_frame()

            col1
2023-01-01   193
2023-01-02   274
2023-01-03   229
2023-01-04   230
2023-01-05   294
...          ...
2023-12-27   205
2023-12-28   226
2023-12-29   251
2023-12-30   219
2023-12-31   270

[365 rows x 1 columns]