In [2]:
# dummy data frame
# import module
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.3.3
2.3.5

In [3]:
# data frame directory
pd.DataFrame({'col1':[1, 2, 3, 4], 
              'col2':[5, 6, 7, 8]})

   col1  col2
0     1     5
1     2     6
2     3     7
3     4     8

In [4]:
# data frame dari numpy array
n_rows = 5
n_cols = 3

arr = np.random.randint(1, 20, size=(n_rows, n_cols))
arr

array([[19,  6,  5],
       [14, 11, 15],
       [ 2, 17, 19],
       [10, 13,  6],
       [15, 10, 14]], dtype=int32)

In [5]:
pd.DataFrame(arr, columns=tuple('ABC'))

    A   B   C
0  19   6   5
1  14  11  15
2   2  17  19
3  10  13   6
4  15  10  14

In [6]:
# data frame dengan memanfaatkan pandas.util.testing

## DEPRICATED ##
# pd.util.testing.makeDataFrame().head()

In [7]:
n_rows = 30 
n_cols = 4 
columns = list('ABCD')

data = np.random.randn(n_rows, n_cols)

df = pd.DataFrame(data, columns=columns)

print(df.head())

          A         B         C         D
0  0.875337 -0.710355 -1.331964 -0.400746
1  0.976080  0.233413  0.204571  0.452279
2  0.635573  1.167275  0.712868  0.763006
3  0.010575 -0.575206 -0.982405  0.198258
4  0.936013 -0.971623  1.696751 -1.512993

In [8]:
## DEPRICATED ##
# pd.util.testing.makeMixedDataFrame().head()

In [9]:
n_rows = 5 

data = {
    'A': np.random.randn(n_rows),                 
    'B': np.arange(1, n_rows + 1),                
    'C': pd.date_range('2024-01-01', periods=n_rows), 
    'D': ['foo', 'bar', 'baz', 'qux', 'quux']    
}

df = pd.DataFrame(data)

print(df.head())

          A  B          C     D
0 -1.371094  1 2024-01-01   foo
1  0.089698  2 2024-01-02   bar
2 -0.047072  3 2024-01-03   baz
3  0.329853  4 2024-01-04   qux
4  0.670721  5 2024-01-05  quux

In [10]:
## DEPRICATED ##
# pd.util.testing.makeTimeDataFrame().head()

In [11]:
n_rows = 30  
n_cols = 4   
columns = list('ABCD')  

time_index = pd.date_range(start='2024-01-01', periods=n_rows, freq='D')  

df = pd.DataFrame(np.random.randn(n_rows, n_cols), index=time_index, columns=columns)

print(df.head())

                   A         B         C         D
2024-01-01  0.589442 -1.733693  0.399502 -0.575249
2024-01-02 -0.303300 -1.141115 -0.607703  1.174852
2024-01-03 -0.703054 -1.166441  0.502935  1.264811
2024-01-04 -0.479966 -1.248220  0.463672  1.221230
2024-01-05  0.687345 -1.662096  1.583860 -1.050345

In [12]:
## DEPRICATED ##
# pd.util.testing.makeMissingDataframe().head()

In [13]:
n_rows = 5
n_cols = 4

data = np.random.randn(n_rows, n_cols)

df = pd.DataFrame(data, columns=list('ABCD'))

df.iloc[0, 1] = np.nan
df.iloc[2, 3] = np.nan
df.iloc[4, 0] = np.nan

print(df.head())

          A         B         C         D
0 -0.569902       NaN  0.944573  0.319148
1 -1.002759  0.215801  0.371394  0.463014
2  0.889851 -0.231135 -1.205551       NaN
3  1.388129  0.059650  1.027467 -0.290064
4       NaN  0.465761  1.370210  0.328508