In [20]:
# formating data frame
# import module
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.3.3
2.3.5

In [21]:
# persiapan data frame 
n_rows = 5
n_cols = 2
cols = ['omset', 'operasional']

df = pd.DataFrame(np.random.randint(1, 20, size=(n_rows, n_cols)), 
                  columns=cols)
df

   omset  operasional
0      4            4
1      2            5
2      9            5
3      6            5
4      5            8

In [22]:
df['omset'] = df['omset'] * 100_000
df['operasional'] = df['operasional'] * 10_000
df

    omset  operasional
0  400000        40000
1  200000        50000
2  900000        50000
3  600000        50000
4  500000        80000

In [23]:
## DEPRICATED ##
# df.index = pd.util.testing.makeDateIndex(n_rows, freq='D')
# df = df.reset_index()
# df = df.rename(columns={'index':'tanggal'})
# df

In [24]:
n_rows = 365  

df = pd.DataFrame(np.random.randint(1, 20, size=(n_rows, 2)), columns=['col1', 'col2'])

df.index = pd.date_range(start='2024-01-01', periods=n_rows, freq='D')

df = df.reset_index().rename(columns={'index': 'tanggal'})

print(df)

       tanggal  col1  col2
0   2024-01-01    17    19
1   2024-01-02    11    14
2   2024-01-03    15     9
3   2024-01-04    14    11
4   2024-01-05     6    17
..         ...   ...   ...
360 2024-12-26     5     1
361 2024-12-27     2     5
362 2024-12-28    17     6
363 2024-12-29    13     7
364 2024-12-30     9    12

[365 rows x 3 columns]

In [25]:
# formatting tampilan data frame
formatku = {'tanggal':'{:%d/%m/%y}', 
            'operasional':'Rp {:.2f}',
            'omset':'Rp {:.2f}'}

laporan = df.style.format(formatku)
laporan

AttributeError: The '.style' accessor requires jinja2

In [ ]:
type(laporan)

In [ ]:

# laporan.hide_index()

In [ ]:
laporan.set_caption('Data Omset dan Operasional')

In [ ]:

## DEPRICATED ##
# laporan.highlight_min('omset', color='pink')
# laporan.highlight_max('omset', color='lightgreen')

# laporan.highlight_min('operasional', color='lightblue')
# laporan.highlight_max('operasional', color='grey')